driver:
  name: dokken
  privileged: true # because Docker and SystemD/Upstart
  chef_version: <%= ENV['CHEF_VERSION'] || "current" %>

transport:
  name: dokken

provisioner:
  name: dokken
  deprecations_as_errors: true

verifier:
  name: inspec

platforms:
- name: dokken/debian-8
  driver:
    image: debian:8
    pid_one_command: /sbin/init
    # intermediate_instructions:
      # - RUN /usr/bin/apt-get update
      # - RUN /usr/bin/apt-get install lsb-release curl -y

- name: debian-9
  driver:
    image: dokken/debian-9
    pid_one_command: /bin/systemd
    # intermediate_instructions:
    #   - RUN /usr/bin/apt-get update
    #   - RUN /usr/bin/apt-get install lsb-release curl -y

- name: centos-6
  driver:
    image: dokken/centos-6
    platform: rhel
    pid_one_command: /sbin/init
    # intermediate_instructions:
    #   - RUN yum -y install which initscripts make

- name: centos-7
  driver:
    image: dokken/centos-7
    platform: rhel
    pid_one_command: /usr/lib/systemd/systemd
    # intermediate_instructions:
    #   - RUN yum -y install lsof which systemd-sysv initscripts make

- name: fedora-latest
  driver:
    image: dokken/fedora-latest
    pid_one_command: /usr/lib/systemd/systemd
    # intermediate_instructions:
    #   - RUN dnf -y install yum which systemd-sysv initscripts

- name: ubuntu-14.04
  driver:
    image: dokken/ubuntu-14.04
    pid_one_command: /sbin/init
    # intermediate_instructions:
    #   - RUN /usr/bin/apt-get update
    #   - RUN /usr/bin/apt-get install curl apt-transport-https lsb-release procps net-tools -y

- name: ubuntu-16.04
  driver:
    image: dokken/ubuntu-16.04
    pid_one_command: /bin/systemd
    # intermediate_instructions:
    #   - RUN /usr/bin/apt-get update
    #   - RUN /usr/bin/apt-get install curl apt-transport-https lsb-release procps net-tools -y

- name: opensuse-leap
  driver:
    image: dokken/opensuse-leap
    pid_one_command: /bin/systemd
    # intermediate_instructions:
    #   - RUN zypper --non-interactive install aaa_base perl-Getopt-Long-Descriptive

suites:
- name: gem
  run_list:
    - recipe[test::gem]
  includes: [centos-7]
- name: global
  run_list: recipe[test::global]
- name: system_install
  run_list: recipe[test::system_install]
- name: user_install
  run_list:
    - recipe[test::user_install]
    - recipe[test::dokken]
