sudo: required
dist: trusty

addons:
  apt:
    sources:
      - chef-current-trusty
    packages:
      - chefdk

# Don't `bundle install` which takes about 1.5 mins
install: echo "skip bundle install"

branches:
  only:
    - master

services: docker

env:
  matrix:
    - INSTANCE=gem-centos-7
    - INSTANCE=global-debian-7
    - INSTANCE=global-debian-8
    - INSTANCE=global-centos-6
    - INSTANCE=global-centos-7
    - INSTANCE=global-centos-7 CHEF_VERSION=12.19.36
    - INSTANCE=global-fedora-latest
    - INSTANCE=global-ubuntu-1404
    - INSTANCE=global-ubuntu-1604
    - INSTANCE=global-opensuse-leap
    - INSTANCE=system-install-debian-7
    - INSTANCE=system-install-debian-8
    - INSTANCE=system-install-centos-6
    - INSTANCE=system-install-centos-7
    - INSTANCE=system-install-fedora-latest
    - INSTANCE=system-install-ubuntu-1404
    - INSTANCE=system-install-ubuntu-1604
    - INSTANCE=system-install-opensuse-leap
    - INSTANCE=user-install-debian-7
    - INSTANCE=user-install-debian-8
    - INSTANCE=user-install-centos-6
    - INSTANCE=user-install-centos-7
    - INSTANCE=user-install-fedora-latest
    - INSTANCE=user-install-ubuntu-1404
    - INSTANCE=user-install-ubuntu-1604
    - INSTANCE=user-install-opensuse-leap

before_script:
  - sudo iptables -L DOCKER || ( echo "DOCKER iptables chain missing" ; sudo iptables -N DOCKER )
  - eval "$(/opt/chefdk/bin/chef shell-init bash)"
  - /opt/chefdk/bin/chef --version
  - /opt/chefdk/bin/cookstyle --version
  - /opt/chefdk/bin/foodcritic --version

script: KITCHEN_LOCAL_YAML=.kitchen.dokken.yml /opt/chefdk/bin/kitchen verify ${INSTANCE}

matrix:
  include:
    - script:
      - /opt/chefdk/bin/chef exec delivery local all
      env: UNIT_AND_LINT=1

notifications:
    slack: northops:FsfnzghB9NkVWXanv0RivJZZ
